### PR TITLE
Fixing SB List endpoint body object issue

### PR DESCRIPTION
**Pull request by HamzaChx**
The list endpoints were missing the data attribute, so I added it to fix this issue.

### CODE REVIEW

**Comment by denisneuf** [comment]
Hi Hamza, where are you come from?

**Comment by HamzaChx** [comment]
Hey, I'm from morocco what about you?

**Comment by denisneuf** [comment]
I am from Spain, may I ask you if you could collaborate on Sponsored Products endpoints version 3? How you use the Amazon Advertising Api? Self business?Enviado desde mi iPhoneEl 2 abr 2023, a las 23:59, Hamza ***@***.***> escribió:﻿
Hey, I'm from morocco what about you?

**Comment by HamzaChx** [comment]
Sure thing, I'll gladly help. I'll get started on it as I intend to use it also.

**Pull request merged**
