### PR TITLE
added marketingstream endpoints

### PR DESCRIPTION
**Pull request by LukasChristoph**

### CODE REVIEW

**Comment by LukasChristoph** [comment]
seems someone else already added marketing stream in the meantime

**Comment by LukasChristoph** [comment]
if  the pull request is not merged, we should enhance the naming and functionality of the existing class.
Stream -> the naming is to generic imo.
we should also use -> data=Utils.convert_body(kwargs.pop('body'), False)

**Comment by drewxa** [comment]
Hi @LukasChristoph 
I believe the handlers are implemented here. https://github.com/denisneuf/python-amazon-ad-api/blob/4bcaf35d6d27594d00f0d1c790aa3f3b7f159e47/ad_api/api/stream.py#L4

**Comment by denisneuf** [comment]
Is already implemented

**Pull request closed without merging**
