### PR TITLE
Updating Keywords, Negative Keywords, Targets and Negative Targets to Version 3

### PR DESCRIPTION
**Pull request by HamzaChx**
Adding the new endpoints to Version 3 of SP API.
Updating Keywords, Negative Keywords, Targets and Negative Targets to Version 3.

Please check to make sure I didn't forget to add anything in docs.

By the way, I've seen that Product Targeting already implements some endpoints but not all, so I added the new ones in the extra product_targeting_v3. Be sure to check it out.

In case something needs to be changed just let me know!

Thank you ;)

### CODE REVIEW

**Review by denisneuf — COMMENTED** [review]
Hi Hamza, will need some time to check but I will let you know later.

**Comment by HamzaChx** [comment]
No worries, just take your time.

**Review by denisneuf — APPROVED** [review]
I will merge and test, thank you

**Comment by HamzaChx** [comment]
Thank you! Let me know if you need any help with anything, I'd be glad to assit :)

**Comment by denisneuf** [comment]
Hi Hamza, 

Could you have a look at sp3:

1) InitialBudgetRecommendation

ad_api/api/sp/budget_initial_recommendation.py

InitialBudgetRecommendation

I am not able to make it work using no matter 3+4 or 3 or 4

json_version = 'application/vnd.spinitialbudgetrecommendation.v3.4+json'

Always get 'status_code': 403 not a valid key=value pair (missing equal-sign) in Authorization header:

2) CampaignsRecommendations

ad_api/api/sp/campaign_consolidated_recommendations.py

I only have access to EU marketplaces and always get 

{
"code":400,
"responseHeaders":null,
"responseBody":null,
"message":"Marketplace is not supported"
}

Can you test in US or JP accounts?

Thank you in advance,

Daniel

**Comment by HamzaChx** [comment]
Hi Daniel,

I'll have a look at it and let you know. Unfortunatly I don't have US or JP accounts im using an EU one for the testing. 
I'll keep in touch.

Best,
Hamza

**Pull request merged**
