### PR TITLE
Add support for creating client using access_token only

### PR DESCRIPTION
**Pull request by drewxa**
this commit introduces a more secure approach to client creation by enabling the generation of clients using only access_tokens (without client secret and long time refresh_token)

### CODE REVIEW

**Comment by drewxa** [comment]
@denisneuf hi! review pls

In some cases, I do not want to disclose secret data such as refresh_token and client_secret, but I am ready to issue access_token, use it for API requests. This PR allows you to use the library in such cases

**Comment by drewxa** [comment]
@denisneuf review pls

**Comment by denisneuf** [comment]
Sorry for my late response @drewxa I will check and let you know as soon as possible. So you will obtain your access_token by yourself and want bypass the api credentials provider submitting directly the token, am I right?

**Comment by denisneuf** [comment]
By the way, could you share with my your snippet to initialize the call to the api, so I can test it?

**Comment by drewxa** [comment]
> So you will obtain your access_token by yourself and want bypass the api credentials provider submitting directly the token, am I right?

yep. This helps in not sharing secrets, with the exception of an access_token, which has a temporary value and expires in a few hours.


```py

import os
os.environ.update(AWS_ENV="PRODUCTION")
from ad_api.api.sp import CampaignsV3
from ad_api.base import Marketplaces


def get_campaigns(access_token: str, profile_id: str):
    creds = dict(
        refresh_token='<dummy string>',
        client_id=os.getenv('CLIENT_ID'),
        client_secret='<dummy string>',
        profile_id=profile_id,
    )

    client = CampaignsV3(
        access_token=access_token,
        credentials=creds,
        marketplace=Marketplaces.US,
    )
    return client.list_campaigns(body='{}').payload

access_token = 'Atza|...'
profile_id = '1234567890'
print(get_campaigns(access_token, profile_id ))
```

**Comment by drewxa** [comment]
@denisneuf it would be great if you can release the edits as soon as possible, we are really waiting

**Review by denisneuf — APPROVED** [review]
ok

**Pull request merged**
