### PR TITLE
Updating Sponsored Brands to Version 4

### PR DESCRIPTION
**Pull request by HamzaChx**
Hello,
I have added some major changes to the repository in sb, as it is currenctly still in the version 3. I have written some logic  for the REST API using the amazon ads api as a source. This is so that I can use the library in other projects.
Check : 
- campaigns_v4.py (implementation of version 4 for the campaign creation)
- ad_groups_v4.py (implementation of version for ad group creation)
- ads.py (ad creation using version 4)
As these changes are quite new, there still might be some bugs. If you find any, please let me know, I will try to fix them as soon as possible. Thank you.

### CODE REVIEW

**Comment by HamzaChx** [comment]
Hi,thanks for reaching out! I closed the pull request because I was still making a few changes. I will open another one when I am done with the testing to make sure everything works.
By the way, would it be possible to send something else as a header? The Version 4 of SB needs an extra header element like so : 
'Accept: application/vnd.sbcampaignresource.v4+json' \
'Content-Type: text/plain' \

**Comment by denisneuf** [comment]
Yes it is prepared by the api customize the “Accept" and  the" Content-Type" header:

Example:

@sp_endpoint('/insights/audiences/{}/overlappingAudiences', method='GET')
def get_insights(self, audienceId: str, version: int = 1, **kwargs) -> ApiResponse:
contentType = 'application/vnd.insightsaudiencesoverlap.v'+str(version)+'+json'
headers = {'Accept': contentType}
return self._request(fill_query_params(kwargs.pop('path'), audienceId), params=kwargs, headers=headers)

json_version = "application/vnd.currencylocalization.v"+str(version)+"+json"
headers = {"Content-Type": json_version}
But be sure you need both, usually the Amazon Advertising API will accept several version in the same endpoint.

If you need any help let me know, by the way, please deep test the endpoints before PR.

Thank you,

Daniel

**Comment by HamzaChx** [comment]
Hi Daniel,

Thanks a lot for your answer, it was quite helpful! I managed to add the missing header and now the endpoints seem to work. I am still working on thoroughly testing them before opening a new PR.

Thanks again,

Hamza

**Comment by HamzaChx** [comment]
Hi Daniel,
while testing the endpoints I have ran into a problem. This is for the POST request to create a campaign. Using Postman to send the request, everything is working. 
But locally testing the endpoint, the response gives a status code 400. with no further information. I wonder where the problem could be.
Do you have any idea how I can fix this problem? 
If you want to take a look at the code, you will find it in the fork  in :  
ad_api/api/sb/campaigns_v4.py

You help would be greatly appreciated. 

Thanks again,
Hamza

**Comment by denisneuf** [comment]
Hi Hamza,

Which body are you using?

Status_code 400 means InvalidArgumentException 400 response.

So this means you are using some invalid argument in your body request.

While testing, you must pass the client debug=True, in that way you can get some logs about what are you sending and receiving

For example, I made a test with the pure raw example of the Amazon documentation:


import logging
import json

from ad_api.api import sponsored_brands
from ad_api.base import AdvertisingApiException

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s:%(levelname)s:%(message)s"
)

logging.info(dir(sponsored_brands))


def sb_campaignsV4(dictionary: dict):
    try:
        result = sponsored_brands.CampaignsV4(debug=True).create_campaigns_v4(

            body=json.dumps(dictionary)

        )

        logging.info(result)

    except AdvertisingApiException as error:
        logging.info(error)


if __name__ == '__main__':

    dictionary = \
    {
        "campaigns": [
            {
                "budgetType": "DAILY",
                "brandEntityId": "string",
                "portfolioId": "string",
                "bidding": {
                    "bidOptimization": True,
                    "bidAdjustmentsByShopperSegment": [
                        {
                            "percentage": 0,
                            "shopperSegment": "NEW_TO_BRAND_PURCHASE"
                        }
                    ],
                    "bidAdjustmentsByPlacement": [
                        {
                            "percentage": 0,
                            "placement": "HOME"
                        }
                    ],
                    "bidOptimizationStrategy": "MAXIMIZE_IMMEDIATE_SALES"
                },
                "endDate": "string",
                "name": "string",
                "state": "ENABLED",
                "productLocation": "SOLD_ON_AMAZON",
                "startDate": "string",
                "budget": 0,
                "tags": {
                    "additionalProp1": "string",
                    "additionalProp2": "string",
                    "additionalProp3": "string"
                }
            }
        ]
    }

    sb_campaignsV4(dictionary)


And what I get is:

2023-03-28 09:41:16,714:INFO:{'User-Agent': 'python-ad-api-0.3.8', 'Amazon-Advertising-API-ClientId': ‘xxx', 'Authorization': 'Bearer xxx, 'Amazon-Advertising-API-Scope': ‘xxx', 'Content-Type': 'application/json', 'Accept': 'application/vnd.sbcampaignresource.v4+json'}
2023-03-28 09:41:16,714:INFO:POST https://advertising-api-eu.amazon.com/sb/v4/campaigns
2023-03-28 09:41:16,714:INFO:{"campaigns": [{"budgetType": "DAILY", "brandEntityId": "string", "portfolioId": "string", "bidding": {"bidOptimization": true, "bidAdjustmentsByShopperSegment": [{"percentage": 0, "shopperSegment": "NEW_TO_BRAND_PURCHASE"}], "bidAdjustmentsByPlacement": [{"percentage": 0, "placement": "HOME"}], "bidOptimizationStrategy": "MAXIMIZE_IMMEDIATE_SALES"}, "endDate": "string", "name": "string", "state": "ENABLED", "productLocation": "SOLD_ON_AMAZON", "startDate": "string", "budget": 0, "tags": {"additionalProp1": "string", "additionalProp2": "string", "additionalProp3": "string"}}]}
2023-03-28 09:41:16,714:INFO:{'_content': b'{"campaigns":{"error":[{"errors":[{"errorType":"INVALID_ARGUMENT","errorValue":{"dateError":{"cause":{"location":"$.startDate","trigger":"string"},"message":"Cannot parse startDate or endDate. Expected format is \'YYYY-MM-DD\'.","reason":"CAMPAIGN_INVALID_DATE_INPUT"}}}],"index":0}],"success":[]}}', '_content_consumed': True, '_next': None, 'status_code': 207, 'headers': {'Server': 'Server', 'Date': 'Tue, 28 Mar 2023 01:41:16 GMT', 'Content-Type': 'application/json', 'Content-Length': '296', 'Connection': 'keep-alive', 'x-amz-rid': ‘xxx', 'x-amzn-RequestId': ‘xxx', 'x-amzn-Remapped-x-amzn-RequestId': ‘xxx', 'x-amzn-Remapped-Content-Length': '296', 'x-amz-apigw-id': 'Cd_VfGJ-DoEFppg=', 'X-Amzn-Trace-Id': 'Root=1-xxx', 'x-amzn-Remapped-Date': 'Tue, 28 Mar 2023 01:41:16 GMT', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload'}, 'raw': <urllib3.response.HTTPResponse object at 0x11054c8b0>, 'url': 'https://advertising-api-eu.amazon.com/sb/v4/campaigns', 'encoding': 'utf-8', 'history': [], 'reason': '', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(seconds=1, microseconds=355220), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x11056c4f0>}
2023-03-28 09:41:16,714:INFO:{'headers': {'headers': {'Server': 'Server', 'Date': 'Tue, 28 Mar 2023 01:41:16 GMT', 'Content-Type': 'application/json', 'Content-Length': '296', 'Connection': 'keep-alive', 'x-amz-rid': xxx', 'x-amzn-RequestId': '014afe34-b94d-4134-936c-18fe21188631', 'x-amzn-Remapped-x-amzn-RequestId': ‘xxx', 'x-amzn-Remapped-Content-Length': '296', 'x-amz-apigw-id': ‘xxx', 'X-Amzn-Trace-Id': ‘Root=xxx', 'x-amzn-Remapped-Date': 'Tue, 28 Mar 2023 01:41:16 GMT', 'Vary': 'Content-Type,Accept-Encoding,User-Agent', 'Strict-Transport-Security': 'max-age=47474747; includeSubDomains; preload'}},
 'next_token': None,
 'payload': {'campaigns': {'error': [{'errors': [{'errorType': 'INVALID_ARGUMENT',
                                                  'errorValue': {'dateError': {'cause': {'location': '$.startDate',
                                                                                         'trigger': 'string'},
                                                                               'message': 'Cannot '
                                                                                          'parse '
                                                                                          'startDate '
                                                                                          'or '
                                                                                          'endDate. '
                                                                                          'Expected '
                                                                                          'format '
                                                                                          'is '
                                                                                          "'YYYY-MM-DD'.",
                                                                               'reason': 'CAMPAIGN_INVALID_DATE_INPUT'}}}],
                                      'index': 0}],
                           'success': []}}}


So I can see that "startDate": "string”, is a invalid argument that create the exception, but endpoint looks is working

Kindest regards,

Daniel.

**Comment by denisneuf** [comment]
Two more thing:

1) Later I realized some people do not find obvious that the body must be a json and send:

```
import json # not imported
dictionary = {}
result = sponsored_brands.CampaignsV4(debug=True).create_campaigns_v4(
    body=dictionary # Instead of json.dumps(dictionary)
)
```

So I start to use an Utils that converts the body if needed and also allow to pass a json file to the body.
You can add in the endpoints passing the data in that way:

from ad_api.base import Client, sp_endpoint, fill_query_params, ApiResponse, **Utils**

return self._request(kwargs.pop('path'), data=**Utils.convert_body(kwargs.pop('body'), False)**, params=kwargs, headers=headers)

2) the Accept header version.
We know now that the json schema version for sb campaigns is: application/vnd.sbcampaignresource.v4+json
But in my experience, in the future, Amazon can release a new version 5 with another schema with new features. Is better you param the version so later the clients could choose the version that they are using. The endpoints that use custom Accept looks like:

```
from ad_api.base import Client, sp_endpoint, fill_query_params, ApiResponse, Utils

class CampaignsV4(Client):
    """
    Version 4 of the SB Campaigns
    """

    @sp_endpoint('/sb/v4/campaigns', method='POST')
    def create_campaigns_v4(self, version: int = 4, **kwargs) -> ApiResponse:
        """
        Creates Sponsored Brands campaigns.
        ...
        """

        json_version = "application/vnd.sbcampaignresource.v"+str(version)+"+json"
        headers = {"Accept": json_version}

        return self._request(kwargs.pop('path'), data=Utils.convert_body(kwargs.pop('body'), False), params=kwargs, headers=headers)
```

Let me know if is clear for you.
Daniel.

**Comment by HamzaChx** [comment]
Hi Daniel,

Thank you so much for your answer, it turned out to be very helpful! Indeed, the problem I had was because the body object wasn't read correctly, but after using the Utils library it worked out fine.
I have also added the version as a parameter like you said, so that it can be easily maintainable in the future.
I think I am almost done with the testing, as soon as I am done I will open a PR.

Thanks again for your support,
Hamza

**Pull request closed without merging**
