### PR TITLE
Feat: make profile_id credential optional in list profiles

### LINKED ISSUE #155: profile_id credential is required to list profiles
**Describe the bug**
The library requires a `profile_id` credential to make the `Profiles().list_profiles()` call, but the [API does not require that](https://advertising.amazon.com/API/docs/en-us/guides/get-started/retrieve-profiles#access-the-profiles-resource). Listing profiles is how one might discover profile IDs, so it doesn't make sense to require one.

**To Reproduce**
```
credentials = {
    "client_id": "...",
    "client_secret": "...",
    "refresh_token": "...",
}
result = Profiles(
    credentials=credentials, marketplace=Marketplaces.NA
).list_profiles(
    apiProgram="report",
    accessLevel="view",
)
```

This code throws an `AttributeError`: 'CredentialProvider' object has no attribute 'credentials'.

**Expected behavior**
The `Profiles().list_profiles()` call should not require `profile_id` in the credentials.

**Workaround**
You can provide a dummy value like `"0"` for the `profile_id`. The library does send the `Amazon-Advertising-API-Scope` header and Amazon validates the value during the `/v2/profiles` call (so it must be an integer), but after validation the value is ignored as far as I can tell.

### PR DESCRIPTION
**Pull request by zsichina**
Closes #155

### CODE REVIEW

**Comment by denisneuf** [comment]
Hi @zsichina, have you tried is working with the different types of credentials? Like from env, code, yml,... I just tried from code omitting the profile_id and is not working, just check that headers are the same if you verify_additional_credentials or not. Can you send an example working to check?

**Comment by zsichina** [comment]
hi @denisneuf,

it worked when `profile_id` attribute existed, but was set to `None`

```
REFRESH_TOKEN = "your-refresh-token"
CLIENT_ID = "your-client-id"
CLIENT_SECRET = "your-client-secret"


def list_profiles(**kwargs):
    credentials = dict(
        refresh_token=REFRESH_TOKEN,
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
        profile_id=None,
    )

    accounts_info = []
    try:
        profile = Profiles(
            credentials=credentials,
            marketplace=Marketplaces.UK,
            verify_additional_credentials=False,
        )
        result = profile.list_profiles(**kwargs)

        for account_info in result.payload:
            accounts_info.append(account_info)
            print(account_info)

    except AdvertisingApiException as error:
        print(error)

    return accounts_info


list_profiles()
```

added new commit and now it works if `profile_id` property doesn't exist (for code, in yml file or if environment variable `AD_API_PROFILE_ID` is not set)


```
def list_profiles(**kwargs):
    credentials = dict(
        refresh_token=REFRESH_TOKEN,
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET,
    )

    accounts_info = []
    try:
        profile = Profiles(
            credentials=credentials,
            marketplace=Marketplaces.UK,
            verify_additional_credentials=False,
        )
        result = profile.list_profiles(**kwargs)

        for account_info in result.payload:
            accounts_info.append(account_info)
            print(account_info)

    except AdvertisingApiException as error:
        print(error)

    return accounts_info
```

**Comment by denisneuf** [comment]
Hi @drewxa could you review this PR and merge if proceed. I plan to make a new release soon. Thank you!

**Comment by drewxa** [comment]
In my view, the code makes some minor adjustments without changing the default behavior. So, my suggestion is to go ahead and merge it.

**Comment by denisneuf** [comment]
@drewxa thank you

**Pull request merged**
