### PR TITLE
Fixed installation error

### PR DESCRIPTION
**Pull request by saleweaver**

### CODE REVIEW

**Review by denisneuf — APPROVED** [review]

**Comment by denisneuf** [comment]
thank you @saleweaver

**Comment by saleweaver** [comment]
It still isn't possible to install a specific version with pip, can you please create a release so that I can use it. Thanks!

**Comment by denisneuf** [comment]
Sure, no problem, hold on.

**Comment by denisneuf** [comment]
You should be able to install 
`pip install python-amazon-ad-api==0.1.3`
Just let me know if is working for you

**Pull request merged**
